services:
  dev-db:
    image: postgres:latest
    container_name: skilltree
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge
