services:
  dev-db:
    image: postgres:latest
    container_name: skilltree
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=arshb
      - POSTGRES_PASSWORD=arshb
      - POSTGRES_DB=skilltree
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge
