export const communities = [
  {
    _id: "1",
    community: "Web Development",
    user: "alice_dev",
    text: "Just discovered this amazing React hook for handling form validation. It's been a game changer for my projects! What are your favorite React hooks?",
    attachment: "https://picsum.photos/500",
    createdAt: new Date("2025-05-27T10:30:00Z"),
    updatedAt: new Date("2025-05-27T10:30:00Z"),
    __v: 0,
  },
  {
    _id: "2",
    community: "Data Science",
    user: "data_wizard",
    text: "Sharing my latest analysis on customer churn prediction using machine learning. The results were quite surprising!",
    attachment: "https://picsum.photos/500",
    createdAt: new Date("2025-05-27T08:15:00Z"),
    updatedAt: new Date("2025-05-27T08:15:00Z"),
    __v: 0,
  },
  {
    _id: "3",
    community: "UX/UI Design",
    user: "design_guru",
    text: "New design system components are ready! Looking for feedback on the color palette and typography choices. What do you think?",
    attachment: "https://picsum.photos/500",
    createdAt: new Date("2025-05-26T16:45:00Z"),
    updatedAt: new Date("2025-05-26T16:45:00Z"),
    __v: 0,
  },
  {
    _id: "4",
    community: "Project Management",
    user: "pm_expert",
    text: "Tips for managing remote teams effectively: 1. Clear communication channels 2. Regular check-ins 3. Defined goals and expectations. What would you add to this list?",
    attachment: "https://picsum.photos/500",
    createdAt: new Date("2025-05-27T09:20:00Z"),
    updatedAt: new Date("2025-05-27T09:20:00Z"),
    __v: 0,
  },
  {
    _id: "5",
    community: "Mobile Development",
    user: "mobile_ninja",
    text: "Flutter vs React Native in 2025 - here's my comparison after building apps in both frameworks. Performance benchmarks included!",
    attachment: "https://picsum.photos/500",
    createdAt: new Date("2025-05-27T07:10:00Z"),
    updatedAt: new Date("2025-05-27T07:10:00Z"),
    __v: 0,
  },
  {
    _id: "6",
    community: "Web Development",
    user: "frontend_dev",
    text: "CSS Grid vs Flexbox - when to use which? Here's a comprehensive guide with practical examples.",
    attachment: "https://picsum.photos/500",
    createdAt: new Date("2025-05-26T14:30:00Z"),
    updatedAt: new Date("2025-05-26T14:30:00Z"),
    __v: 0,
  },
  {
    _id: "7",
    community: "Data Science",
    user: "ml_researcher",
    text: "Just published my findings on neural network optimization techniques. The performance improvements are significant!",
    attachment: "https://picsum.photos/500",
    createdAt: new Date("2025-05-26T11:00:00Z"),
    updatedAt: new Date("2025-05-26T11:00:00Z"),
    __v: 0,
  },
  {
    _id: "8",
    community: "Digital Marketing",
    user: "marketing_pro",
    text: "SEO trends for 2025: Core Web Vitals are more important than ever. Here's how to optimize your site for better rankings.",
    attachment: "https://picsum.photos/500",
    createdAt: new Date("2025-05-25T13:45:00Z"),
    updatedAt: new Date("2025-05-25T13:45:00Z"),
    __v: 0,
  },
];
